export const C = {
  bg:       "#08080e",
  bgDeep:   "#050509",
  sidebar:  "rgba(10,10,18,0.85)",
  card:     "rgba(22,22,34,0.65)",
  cardHov:  "rgba(30,30,46,0.85)",
  border:   "rgba(255,255,255,0.07)",
  borderHov:"rgba(255,255,255,0.14)",
  text:     "#f2f0ff",
  textSub:  "#9a96c0",
  textMuted:"#524e78",
  pink:     "#f04fff",
  pinkDim:  "#f04fff55",
  pinkGlow: "#f04fff12",
  cyan:     "#33e0ff",
};

// Brand icons fall back to styled vendor initials to keep the bundle lightweight.
export const ICONS = {};

export const VENDORS = {
  "OpenAI": { color: "#10a37f", bg: "#0a2e21" },
  "Anthropic": { color: "#d97706", bg: "#2d1e06" },
  "Google": { color: "#4285f4", bg: "#0a1a3d" },
  "Meta": { color: "#0081fb", bg: "#00152e" },
  "Mistral AI": { color: "#f97316", bg: "#2d1200" },
  "xAI": { color: "#e2e8f0", bg: "#141418" },
  "DeepSeek": { color: "#7c6af7", bg: "#12103a" },
  "Alibaba": { color: "#ff6a00", bg: "#2d1200" },
  "Microsoft": { color: "#00a4ef", bg: "#001a2e" },
  "Cohere": { color: "#39d353", bg: "#052210" },
  "TII": { color: "#a78bfa", bg: "#1a1030", initial: "TII" },
  "01.AI": { color: "#f472b6", bg: "#2d0a1a", initial: "01.AI" },
  "AI21 Labs": { color: "#fbbf24", bg: "#2d2000", initial: "AI21" },
  "Databricks": { color: "#ff3621", bg: "#2d0800" },
  "Nous Research": { color: "#c084fc", bg: "#1e0a30", initial: "NR" },
  "Upstage": { color: "#fde68a", bg: "#2d2800", initial: "UP" },
  "Perplexity": { color: "#20d5b2", bg: "#002822" },
  "IBM": { color: "#4589ff", bg: "#000e2d" },
  "Moonshot AI": { color: "#22d3ee", bg: "#00202e", initial: "KM" },
  "NVIDIA": { color: "#76b900", bg: "#0a1a00" },
};

export const gv = n => VENDORS[n] || { color: C.pink, bg: "#1a0a2e", initial: n.slice(0,2).toUpperCase() };

export const LLM_LIST = [
  { id:"gpt55",         name:"GPT-5.5",           vendor:"OpenAI",       tags:["flagship","2026","reasoning"] },
  { id:"gpt54",         name:"GPT-5.4",           vendor:"OpenAI",       tags:["coding","computer use"] },
  { id:"gpt5",          name:"GPT-5",             vendor:"OpenAI",       tags:["multimodal","1M ctx"] },
  { id:"gpt-oss-120b",  name:"GPT-OSS 120B",      vendor:"OpenAI",       tags:["open source","MoE"] },
  { id:"gpt-oss-20b",   name:"GPT-OSS 20B",       vendor:"OpenAI",       tags:["open source","lokalny"] },
  { id:"claude-opus47", name:"Claude Opus 4.7",   vendor:"Anthropic",    tags:["flagship","kod","agenty"] },
  { id:"claude-opus46", name:"Claude Opus 4.6",   vendor:"Anthropic",    tags:["agentic","reasoning"] },
  { id:"claude-sonnet46",name:"Claude Sonnet 4.6",vendor:"Anthropic",    tags:["balans","1M ctx"] },
  { id:"claude-haiku45",name:"Claude Haiku 4.5",  vendor:"Anthropic",    tags:["szybki","tani"] },
  { id:"claude-fable5", name:"Claude Fable 5",    vendor:"Anthropic",    tags:["reasoning","1M ctx","2026"] },
  { id:"gemini31-pro",  name:"Gemini 3.1 Pro",    vendor:"Google",       tags:["flagship","multimodal"] },
  { id:"gemini35-flash",name:"Gemini 3.5 Flash",  vendor:"Google",       tags:["szybki","2026","agenty"] },
  { id:"gemini31-lite", name:"Gemini 3.1 Flash-Lite",vendor:"Google",    tags:["tani","edge"] },
  { id:"gemma3",        name:"Gemma 3",           vendor:"Google",       tags:["open source","lokalny"] },
  { id:"llama4-maverick",name:"Llama 4 Maverick", vendor:"Meta",         tags:["open source","MoE"] },
  { id:"llama4-scout",  name:"Llama 4 Scout",     vendor:"Meta",         tags:["10M ctx","open source"] },
  { id:"mistral-large3",name:"Mistral Large 3",   vendor:"Mistral AI",   tags:["europejski","kod","2026"] },
  { id:"mistral-small3",name:"Mistral Small 3.1", vendor:"Mistral AI",   tags:["szybki","tani"] },
  { id:"grok3",         name:"Grok 3",            vendor:"xAI",          tags:["real-time","reasoning"] },
  { id:"grok3-mini",    name:"Grok 3 Mini",       vendor:"xAI",          tags:["szybki","tani"] },
  { id:"deepseek-v4pro",name:"DeepSeek V4 Pro",   vendor:"DeepSeek",     tags:["flagship","MIT","2026"] },
  { id:"deepseek-v4f",  name:"DeepSeek V4 Flash", vendor:"DeepSeek",     tags:["tani","szybki"] },
  { id:"deepseek-r2",   name:"DeepSeek R2",       vendor:"DeepSeek",     tags:["rozumowanie","open source"] },
  { id:"qwen37-max",    name:"Qwen 3.7 Max",      vendor:"Alibaba",      tags:["flagship","2026","kod"] },
  { id:"qwen3-coder",   name:"Qwen 3 Coder",      vendor:"Alibaba",      tags:["kod","open source"] },
  { id:"phi4",          name:"Phi-4",             vendor:"Microsoft",    tags:["mały","wydajny","lokalny"] },
  { id:"command-r-plus",name:"Command R+ 2025",   vendor:"Cohere",       tags:["RAG","enterprise"] },
  { id:"cohere-north",  name:"North Mini Code",   vendor:"Cohere",       tags:["kod","nowy","2026"] },
  { id:"kimi-k2",       name:"Kimi K2",           vendor:"Moonshot AI",  tags:["1T params","MoE","kod"] },
  { id:"kimi-k26",      name:"Kimi K2.6",         vendor:"Moonshot AI",  tags:["2026","coding","tani"] },
  { id:"nemotron550b",  name:"Nemotron 3 Ultra 550B",vendor:"NVIDIA",    tags:["ultra","2026","enterprise"] },
  { id:"sonar-pro",     name:"Sonar Pro 2025",    vendor:"Perplexity",   tags:["real-time","wyszukiwanie"] },
  { id:"granite33",     name:"Granite 3.3",       vendor:"IBM",          tags:["enterprise","bezpieczny"] },
  { id:"jamba15",       name:"Jamba 1.5",         vendor:"AI21 Labs",    tags:["długi kontekst","hybryda"] },
];

export const NAV_ITEMS = [
  { id:"wszystkie",   label:"WSZYSTKIE",  icon:"▦" },
  { id:"OpenAI",      label:"OPENAI",     icon:null },
  { id:"Anthropic",   label:"ANTHROPIC",  icon:null },
  { id:"Google",      label:"GOOGLE",     icon:null },
  { id:"Meta",        label:"META",       icon:null },
  { id:"Mistral AI",  label:"MISTRAL",    icon:null },
  { id:"xAI",         label:"XAI",        icon:null },
  { id:"DeepSeek",    label:"DEEPSEEK",   icon:null },
  { id:"Alibaba",     label:"ALIBABA",    icon:null },
  { id:"Microsoft",   label:"MICROSOFT",  icon:null },
  { id:"Moonshot AI", label:"KIMI",       icon:null },
  { id:"NVIDIA",      label:"NVIDIA",     icon:null },
  { id:"inne",        label:"POZOSTAŁE",  icon:"⋯" },
];
export const INNE = ["Cohere","TII","01.AI","AI21 Labs","Databricks","Nous Research","Upstage","Perplexity","IBM"];
